netbox_license/urls.py
from django.urls import include, path
from utilities.urls import get_model_urls
from . import views


urlpatterns = [
    # Licenses
    path('licenses/',include(get_model_urls('netbox_license', 'license', detail=False))),
    path('licenses/<int:pk>/',include(get_model_urls('netbox_license', 'license'))),

    # License type
    path('types/', include(get_model_urls('netbox_license', 'licensetype', detail=False))),
    path('types/<int:pk>/', include(get_model_urls('netbox_license', 'licensetype'))),

    # License Assignments 
    path('assignments/',include(get_model_urls('netbox_license', 'licenseassignment',detail=False))),
    path('assignments/<int:pk>/',include(get_model_urls('netbox_license', 'licenseassignment'))),
    
]

netbox_license/models/licensetype.py
from django.db import models
from netbox.models import NetBoxModel
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from ..choices import (
    VolumeTypeChoices,
    PurchaseModelChoices,
    LicenseModelChoices,
    VolumeRelationChoices,
)
class LicenseType(NetBoxModel):
    name = models.CharField(max_length=255)

    slug = models.SlugField(unique=True)
    
    manufacturer = models.ForeignKey(
        to= 'dcim.Manufacturer',
        on_delete=models.PROTECT,
        related_name="license_types"
    )

    product_code = models.CharField(max_length=255, blank=True, null=True)

    ean_code = models.CharField(
    "EAN code",
    max_length=255,
    blank=True,
    null=True
)

    volume_type = models.CharField(
        max_length=20, 
        choices=VolumeTypeChoices
    )

    volume_relation = models.CharField(
        max_length=20,
        choices=VolumeRelationChoices,
        blank=True,
        null=True,
        help_text="What the license volume applies to (e.g., Users, Cores, etc.)."
    )

    license_model = models.CharField(
        max_length=20,
        choices=LicenseModelChoices,
        default="base"
    )
    base_license = models.ForeignKey(
        'self',
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="expansions",
        help_text="Only for expansion licenses. Must reference a base license."
    )
    purchase_model = models.CharField(max_length=20, choices=PurchaseModelChoices, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    comments = models.TextField(blank=True, null=True)

    clone_fields = ['manufacturer', 'volume_type', 'license_model', 'purchase_model']

    def clean(self):
        super().clean()

        if self.license_model == LicenseModelChoices.EXPANSION:
            if not self.base_license:
                raise ValidationError({
                    "base_license": "An Expansion license type must reference a Base license."
                })
            if self.base_license.license_model != LicenseModelChoices.BASE:
                raise ValidationError({
                    "base_license": "Base License must be of type 'base'."
                })

        elif self.license_model == LicenseModelChoices.BASE:
            if self.base_license is not None:
                raise ValidationError({
                    "base_license": "Only Expansion licenses can reference a base license."
                })

        if self.pk:
            original = LicenseType.objects.get(pk=self.pk)
            has_licenses = self.licenses.exists()

            if has_licenses:
                if original.license_model != self.license_model:
                    raise ValidationError({
                        "license_model": "Cannot change license model: there are existing licenses linked to this license type."
                    })

                if original.volume_type != self.volume_type:
                    raise ValidationError({
                        "volume_type": "Cannot change volume type: there are existing licenses linked to this license type."
                    })

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("plugins:netbox_license:licensetype", args=[self.pk])
    
    class Meta:
        verbose_name = "License Type"
        verbose_name_plural = "License Types"

netbox_license/views/license.py
from netbox.views import generic
from utilities.views import register_model_view
from django.db.models import OuterRef, Subquery, Sum, Case, When, BooleanField, Value
from django.db.models.functions import Coalesce
from netbox_license.models.license import License
from netbox_license.models.licenseassignment import LicenseAssignment
from .. import tables
from ..forms.filtersets import LicenseFilterForm
from ..forms.bulk_edit import LicenseBulkEditForm
from ..forms.bulk_import import LicenseImportForm
from ..forms.models import LicenseForm
from netbox_license.filtersets.licenses import LicenseFilterSet



__all__ = (
    'LicenseView',
    'LicenseListView',
    'LicenseEditView',
    'LicenseDeleteView',
    'LicenseBulkImportView',
    'LicenseBulkEditView',
    'LicenseBulkDeleteView',
)

# -------------------- Object Views --------------------

@register_model_view(License)
class LicenseView(generic.ObjectView):
    """View for displaying a single License"""
    queryset = License.objects.all()

    def get_extra_context(self, request, instance):
        context = super().get_extra_context(request, instance)
        return context

@register_model_view(License, 'list', path='', detail=False)
class LicenseListView(generic.ObjectListView):
    """View for displaying a list of Licenses"""
    queryset = License.objects.all()
    table = tables.LicenseTable
    filterset = LicenseFilterSet
    filterset_form = LicenseFilterForm

    def get_queryset(self, request):
        qs = super().get_queryset(request)

        assignments_sum = LicenseAssignment.objects.filter(
            license=OuterRef('pk')
        ).values('license').annotate(
            total=Sum('volume')
        ).values('total')

        return qs.annotate(
            is_parent_license_value=Case(
                When(sub_licenses__isnull=False, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            ),
            is_child_license_value=Case(
                When(parent_license__isnull=False, then=Value(True)),
                default=Value(False),
                output_field=BooleanField()
            ),
            assigned_count_value=Coalesce(Subquery(assignments_sum), 0)
        ).distinct()



@register_model_view(License, 'edit')
@register_model_view(License, 'add', detail=False)
class LicenseEditView(generic.ObjectEditView):
    """View for creating or editing a license."""
    queryset = License.objects.all()
    form = LicenseForm
    default_return_url = 'plugins:netbox_license:license_list'

    def get_initial(self):
        initial = super().get_initial()
        request = self.request

        if request.GET.get("parent_license"):
            initial["parent_license"] = request.GET.get("parent_license")
        if request.GET.get("license_type"):
            initial["license_type"] = request.GET.get("license_type")
        
        return initial



@register_model_view(License, 'delete')
class LicenseDeleteView(generic.ObjectDeleteView):
    """View for deleting a license"""
    queryset = License.objects.all()
    default_return_url = 'plugins:netbox_license:license_list'

# -------------------- bulk --------------------

@register_model_view(License, 'bulk_import', path='import', detail=False)
class LicenseBulkImportView(generic.BulkImportView):
    """View for bulk importing licenses."""
    queryset = License.objects.all()
    model_form = LicenseImportForm


@register_model_view(License, 'bulk_edit', path='edit', detail=False)
class LicenseBulkEditView(generic.BulkEditView):
    """View for bulk editing licenses."""
    queryset = License.objects.all()
    filterset = LicenseFilterSet
    table = tables.LicenseTable
    form = LicenseBulkEditForm
    default_return_url = 'plugins:netbox_license:license_list'


@register_model_view(License, 'bulk_delete', path='delete', detail=False)
class LicenseBulkDeleteView(generic.BulkDeleteView):
    """View for bulk deleting licenses."""
    queryset = License.objects.all()
    table = tables.LicenseTable

netbox_license/views/licenseassignment.py
from netbox.views import generic
from utilities.views import register_model_view
from netbox_license.models.licenseassignment import LicenseAssignment
from .. import tables
from netbox_license.filtersets.licenseassignments import LicenseAssignmentFilterSet
from ..forms.models import LicenseAssignmentForm
from ..forms.bulk_edit import LicenseAssignmentBulkEditForm
from ..forms.bulk_import import LicenseAssignmentImportForm
from ..forms.filtersets import LicenseAssignmentFilterForm


__all__ = (
    'LicenseAssignmentListView',
    'LicenseAssignmentView',
    'LicenseAssignmentEditView',
    'LicenseAssignmentDeleteView',

)

# -------------------- Object Views --------------------
@register_model_view(LicenseAssignment)
class LicenseAssignmentView(generic.ObjectView):
    """View to display details of a license assignment."""
    queryset = LicenseAssignment.objects.prefetch_related("license", "device")

    def get_extra_content(self, request, instance):
        context = super().get_extra_content(request, instance)
        return context


@register_model_view(LicenseAssignment, 'list', path='', detail=False)
class LicenseAssignmentListView(generic.ObjectListView):
    """View to list all assigned licenses with advanced filters."""
    queryset = LicenseAssignment.objects.prefetch_related("license", "device")
    table = tables.LicenseAssignmentTable
    filterset = LicenseAssignmentFilterSet
    filterset_form = LicenseAssignmentFilterForm 

@register_model_view(LicenseAssignment, 'edit')
@register_model_view(LicenseAssignment, 'add', detail=False)
class LicenseAssignmentEditView(generic.ObjectEditView):
    """View to create or edit a license assignment."""
    queryset = LicenseAssignment.objects.all()
    form = LicenseAssignmentForm
    default_return_url = 'plugins:netbox_license:licenseassignment_list'



@register_model_view(LicenseAssignment, 'delete')
class LicenseAssignmentDeleteView(generic.ObjectDeleteView):
    """View to delete a license assignment."""
    queryset = LicenseAssignment.objects.all()
    default_return_url = 'plugins:netbox_license:licenseassignment_list'

# -------------------- bulk --------------------

@register_model_view(LicenseAssignment, 'bulk_import', path='import', detail=False)
class LicenseAssignmentBulkImportView(generic.BulkImportView):
    """View for bulk importing license assignments."""
    queryset = LicenseAssignment.objects.all()
    model_form = LicenseAssignmentImportForm

@register_model_view(LicenseAssignment, 'bulk_edit', path='edit', detail=False)
class LicenseAssignmentBulkEditView(generic.BulkEditView):
    """View for bulk editing license assignments."""
    queryset = LicenseAssignment.objects.all()
    filterset = LicenseAssignmentFilterSet
    table = tables.LicenseAssignmentTable
    form = LicenseAssignmentBulkEditForm
    default_return_url = 'plugins:netbox_license:licenseassignment_list'

@register_model_view(LicenseAssignment, 'bulk_delete', path='delete', detail=False)
class LicenseAssignmentBulkDeleteView(generic.BulkDeleteView):
    """View for bulk deleting license assignments."""
    queryset = LicenseAssignment.objects.all()
    table = tables.LicenseAssignmentTable
    default_return_url = 'plugins:netbox_license:licenseassignment_list'

netbox_license/views/licensetype.py
from netbox.views import generic
from utilities.views import register_model_view
from netbox_license.models.licensetype import LicenseType
from .. import tables
from netbox_license.filtersets.licensetypes import LicenseTypeFilterSet
from ..forms.filtersets import LicenseTypeFilterForm
from ..forms.models import LicenseTypeForm
from ..forms.bulk_edit import LicenseTypeBulkEditForm
from ..forms.bulk_import import LicenseTypeImportForm
from django.db.models import Count

__all__ = (
    'LicenseTypeView',
    'LicenseTypeListView',
    'LicenseTypeEditView',
    'LicenseTypeDeleteView',
    'LicenseTypeBulkImportView',
    'LicenseTypeBulkEditView',
    'LicenseTypeBulkDeleteView',
)

# -------------------- Object Views --------------------

@register_model_view(LicenseType)
class LicenseTypeView(generic.ObjectView):
    """View for displaying a single License Type"""
    queryset = LicenseType.objects.all()

@register_model_view(LicenseType, 'list', path='', detail=False)
class LicenseTypeListView(generic.ObjectListView):
    queryset = LicenseType.objects.annotate(license_count=Count('licenses', distinct=True))
    table = tables.LicenseTypeTable
    filterset = LicenseTypeFilterSet
    filterset_form = LicenseTypeFilterForm


@register_model_view(LicenseType, 'add', detail=False)
@register_model_view(LicenseType, 'edit')
class LicenseTypeEditView(generic.ObjectEditView):
    queryset = LicenseType.objects.all()
    form = LicenseTypeForm
    default_return_url = 'plugins:netbox_license:licensetype_list'


@register_model_view(LicenseType, 'delete')
class LicenseTypeDeleteView(generic.ObjectDeleteView):
    queryset = LicenseType.objects.all()
    default_return_url = 'plugins:netbox_license:licensetype_list'

# -------------------- bulk --------------------

@register_model_view(LicenseType, 'bulk_import', path='import', detail=False)
class LicenseTypeBulkImportView(generic.BulkImportView):
    queryset = LicenseType.objects.all()
    model_form = LicenseTypeImportForm


@register_model_view(LicenseType, 'bulk_edit', path='edit', detail=False)
class LicenseTypeBulkEditView(generic.BulkEditView):
    queryset = LicenseType.objects.all()
    filterset = LicenseTypeFilterSet
    table = tables.LicenseTypeTable
    form = LicenseTypeBulkEditForm
    default_return_url = 'plugins:netbox_license:licensetype_list'


@register_model_view(LicenseType, 'bulk_delete', path='delete', detail=False)
class LicenseTypeBulkDeleteView(generic.BulkDeleteView):
    queryset = LicenseType.objects.all()
    table = tables.LicenseTypeTable
    default_return_url = 'plugins:netbox_license:licensetype_list'

netbox_license/templates/netbox_license/license.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load humanize %}
{% load plugins %}

{% block title %}
  {{ object.license_key }}
{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% if object.license_type %}
    <li class="breadcrumb-item">
      <a href="{% url 'plugins:netbox_license:license_list' %}?license_type_id={{ object.license_type.pk }}">
        {{ object.license_type }}
      </a>
    </li>
  {% endif %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <h5 class="card-header">License Details</h5>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">License Type</th>
          <td>{{ object.license_type|linkify }}</td>
        </tr>
        <tr>
          <th>License Key</th>
          <td class="font-monospace">{{ object|linkify }}</td>
        </tr>
        <tr>
          <th scope="row">Product Key</th>
          <td class="font-monospace">{{ object.product_key|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Serial Number</th>
          <td>{{ object.serial_number|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">License Manufacturer</th>
          <td>{{ object.license_type.manufacturer|linkify|placeholder }}</td>  <!-- ✅ -->
        </tr>        
        <tr>
          <th scope="row">Volume Type</th>
          <td>{{ object.license_type.get_volume_type_display }}</td>
        </tr>        
        <tr>
          <th scope="row">Volume Limit</th>
          <td>
            {% if object.volume_type == 'UNLIMITED' %}
              Unlimited
            {% else %}
              {{ object.volume_limit }}
            {% endif %}
          </td>
        </tr>
        <tr>
          <th scope="row">Current Usage</th>
          <td>{{ object.usage_display }}</td>
        </tr>
        {% if object.parent_license %}
        <tr>
          <th scope="row">Parent License</th>
          <td>{{ object.parent_license|linkify }}</td>
        </tr>
        {% endif %}
        {% if object.purchase_date %}
        <tr>
          <th scope="row">Purchase Date</th>
          <td>{{ object.purchase_date|date:"Y-m-d" }}</td>
        </tr>
        {% endif %}

        {% if object.expiry_date %}
        <tr>
          <th scope="row">Expiry Date</th>
          <td>{{ object.expiry_date|date:"Y-m-d" }}</td>
        </tr>
        {% endif %}

        <tr>
          <th scope="row">Expiry Status</th>
          <td>
            {% include "netbox_license/inc/license_progressbar.html" with record=object %}
          </td>
        </tr>
        <tr>
          <th scope="row">Description</th>
          <td>{{ object.description|placeholder }}</td>
        </tr>
      </table>
    </div>

    {% include 'inc/panels/custom_fields.html' %}
  </div>

  <div class="col-md-6">
    <div class="card">
      <h2 class="card-header d-flex justify-content-between align-items-center">
        Assigned Devices ({{ object.usage_display }})
        <div class="card-actions">
          <a href="{% url 'plugins:netbox_license:licenseassignment_add' %}?license={{ object.id }}&manufacturer={{ object.license_type.manufacturer.id }}" class="btn btn-ghost-primary btn-sm">
            <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add Assignment
          </a>
        </div>
      </h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Device</th>
            <th>Device Manufacturer</th>
            <th>Assigned On</th>
            <th>Volume</th>
          </tr>
        </thead>
        <tbody>
          {% for assignment in object.assignments.all %}
          <tr>
            <td>{{ assignment.device|linkify|placeholder }}</td>
            <td>{{ assignment.device_manufacturer|linkify|placeholder }}</td>
            <td>{{ assignment.assigned_on|date:"Y-m-d" }}</td>
            <td>{{ assignment.volume }}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="4" class="text-muted">No assignments found.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    {% if object.license_type.license_model != 'expansion' %}
    <div class="card mt-3">
      <h2 class="card-header d-flex justify-content-between align-items-center">
        Child Licenses
        <div class="card-actions">
          <a href="{% url 'plugins:netbox_license:license_add' %}?parent_license={{ object.pk }}&manufacturer={{ object.license_type.manufacturer.pk }}" class="btn btn-ghost-primary btn-sm">
            <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add Child License
          </a>
        </div>
      </h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>License Key</th>
            <th>License Type</th>
            <th>Volume</th>
            <th>Expiry Date</th>
          </tr>
        </thead>
        <tbody>
          {% for child in object.sub_licenses.all %}
          <tr>
            <td>{{ child|linkify }}</td>
            <td>{{ child.license_type|linkify|placeholder }}</td>
            <td>
              {% if child.license_type.volume_type == 'unlimited' %}
                Unlimited
              {% else %}
                {{ child.volume_limit|placeholder }}
              {% endif %}
            </td>
            <td>{{ child.expiry_date|date:"Y-m-d"|placeholder }}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="4" class="text-muted">No child licenses found.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}

    {% include 'inc/panels/tags.html' %}
    {% include 'inc/panels/comments.html' %}
  </div>
</div>
<div class="row mb-3">
  <div class="col col-md-12">
    {% plugin_full_width_page object %}
  </div>
</div>
{% endblock %}

netbox_license/templates/netbox_license/licenseassignment.html
{% extends 'generic/object.html' %}
{% load helpers %}

{% block title %}License Assignment ID {{ object.pk }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% if object.license.license_type %}
    <li class="breadcrumb-item">
      <a href="{% url 'plugins:netbox_license:licenseassignment_list' %}?license__license_type_id={{ object.license.license_type.pk }}">
      {{ object.license.license_type }}
      </a>
    </li>
  {% endif %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <h5 class="card-header">License Details</h5>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">Name</th>
          <td>{{ object.license.license_type|linkify }}</td>
        </tr>
        <tr>
          <th scope="row">License Key</th>
          <td class="font-monospace">{{ object.license|linkify }}</td>
        </tr>
        <tr>
          <th scope="row">Product Key</th>
          <td class="font-monospace">{{ object.license.product_key|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Serial Number</th>
          <td>{{ object.license.serial_number|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">License Manufacturer</th>
          <td>{{ object.license.license_type.manufacturer|linkify|placeholder }}</td>  <!-- ✅ -->
        </tr>
        <tr>
          <th scope="row">Volume Type</th>
          <td>{{ object.license.license_type.get_volume_type_display }}</td>
        </tr>
        <tr>
          <th scope="row">Parent License</th>
          <td>{{ object.license.parent_license|linkify|default:"None" }}</td>
        </tr>
        <tr>
          <th scope="row">Purchase Date</th>
          <td>{{ object.license.purchase_date|date:"Y-m-d" }}</td>
        </tr>
        <tr>
          <th scope="row">Expiry Date</th>
          <td>{{ object.license.expiry_date|date:"Y-m-d" }}</td>
        </tr>
      </table>
    </div>
  </div>

  <!-- Assignment Details -->
  <div class="col-md-6">
    <div class="card">
      <h5 class="card-header">Assignment Details</h5>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">Device</th>
          <td>{{ object.device|linkify|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Device Manufacturer</th>
          <td>{{ object.device.device_type.manufacturer|linkify|placeholder }}</td>
          {# Alternatively: <td>{{ object.device_manufacturer|linkify|placeholder }}</td> #}
        </tr>
        <tr>
          <th scope="row">Assigned On</th>
          <td>{{ object.assigned_on|date:"Y-m-d" }}</td>
        </tr>
        <tr>
          <th scope="row">Volume</th>
          <td>{{ object.volume }}</td>
        </tr>
        <tr>
          <th scope="row">Description</th>
          <td>{{ object.description|placeholder }}</td>
        </tr>
      </table>
    </div>
  </div>
</div>
{% endblock %}

netbox_license/templates/netbox_license/licensetype.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load humanize %}
{% load plugins %}

{% block title %}
  {{ object.name }}
{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li class="breadcrumb-item">
    <a href="{% url 'plugins:netbox_license:licensetype_list' %}?manufacturer_id={{ object.manufacturer.pk }}">
      {{ object.manufacturer }}
    </a>
  </li>
  
{% endblock %}

{% block content %}
<div class="row mb-3">
  <div class="col-md-6">
    <div class="card">
      <h5 class="card-header">License Type Details</h5>
      <table class="table table-hover attr-table">
        <tr>
          <th scope="row">Name</th>
          <td>{{ object.name|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Slug</th>
          <td>{{ object.slug }}</td>
        </tr>
        <tr>
          <th scope="row">Manufacturer</th>
          <td>{{ object.manufacturer|linkify|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Product Code</th>
          <td>{{ object.product_code|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">EAN Code</th>
          <td>{{ object.ean_code|placeholder }}</td>
        </tr>
        <tr>
          <th scope="row">Volume Type</th>
          <td>{{ object.get_volume_type_display }}</td>
        </tr>
        {% if object.volume_relation %}
        <tr>
          <th scope="row">Volume Relation</th>
          <td>{{ object.get_volume_relation_display }}</td>
        </tr>
        {% endif %}
        <tr>
          <th scope="row">License Model</th>
          <td>{{ object.get_license_model_display }}</td>
        </tr>
        {% if object.base_license %}
        <tr>
          <th scope="row">Base License</th>
          <td>{{ object.base_license|linkify }}</td>
        </tr>
        {% endif %}
        <tr>
          <th scope="row">Purchase Model</th>
          <td>{{ object.get_purchase_model_display|default:"N/A" }}</td>
        </tr>
        <tr>
          <th scope="row">Description</th>
          <td>{{ object.description|placeholder }}</td>
        </tr>
      </table>
    </div>

    {% include 'inc/panels/custom_fields.html' %}
    
    {% include 'inc/panels/comments.html' %}
    {% include 'inc/panels/tags.html' %}
    {% plugin_left_page object %}
  </div>
  <div class="col-md-6">
    <div class="card">
      <h2 class="card-header d-flex justify-content-between align-items-center">
        Expansion Types ({{ object.expansions.count }})
        <div class="card-actions">
            <a href="{% url 'plugins:netbox_license:licensetype_add' %}?license_model=expansion&base_license={{ object.pk }}" class="btn btn-ghost-primary btn-sm">
            <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add Expansion Type
          </a>
        </div>
      </h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Manufacturer</th>
            <th>License Model</th>
          </tr>
        </thead>
        <tbody>
          {% for expansion in object.expansions.all %}
          <tr>
            <td>{{ expansion|linkify }}</td>
            <td>{{ expansion.manufacturer|linkify|placeholder }}</td>
            <td>{{ expansion.get_license_model_display }}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="3" class="text-muted">No expansion licenses found.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  

    {% plugin_right_page object %}
  </div>
</div>
<div class="row mb-3">
  <div class="col col-md-12">
    {% plugin_full_width_page object %}
  </div>
</div>
{% endblock %}